import ProjectDescription

// MARK: Workspace
let workspace = Workspace(
    name: "PracticeProject",
    projects: ["./"],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
